### ISSUE TITLE
Provide pinout for X-4 V1.1 motherboard

### ISSUE THREAD

**Issue by cb-agotchi** [QIDITECH/QIDI_MAX3#13]
Please provide pinout and definitions for X-4 V1.1 motherboard

**Comment by QIDITECH** [comment]
Please contact our after-sales service.
https://qidi3d.com/pages/warranty-policy-after-sales-support

**Comment by Phil1988** [comment]
This comment looks not very helpful to me, so here is a pinout for everyone in the future:
![image](https://github.com/QIDITECH/QIDI_MAX3/assets/6054234/1007f900-0c15-46d7-ace7-a1872bed797c)
