### ISSUE TITLE
Info during printing

### ISSUE THREAD

**Issue by czertique** [QIDITECH/QIDI_MAX3#16]
Could you please consider adding current and total layer numbers to display UI during print? Having it just above the progress bar (next to the progress % indicator) would probably work. Something like: "78% - layer 104/143" or similar.

Also, showing the amount of material currently consumed would be great.

Thank you!

**Comment by QIDITECH** [comment]
Sorry, there is not enough space on the page to put these parameters, we will not consider adding them for now.
