### ISSUE TITLE
Filament wechsel

### ISSUE THREAD

**Issue by Anelke** [QIDITECH/QIDI_MAX3#18]
Hallo 
Ich und mein x max 3 sind uns noch nicht einig! Beim Filament wechsel und neu laden drückt er nicht genug Filament raus.
Wenn ich dann den Druck wieder aufnehme dauert es lange bis Filament kommt. Meine bitte was kann ich machen damit er bei der Aufnahme des Druckes auch sofort Filament hat. Desweiteren würde ich gerne einen Reinigungsturm machen weiß aber nicht wie.

LG Andre und schöne Feiertage!!!!

Hello
Me and my x max 3 still don't agree! When changing and reloading filament it doesn't push out enough filament.
When I start printing again it takes a long time for filament to come out. My request, what can I do so that it has filament immediately when the print is taken? I would also like to make a cleaning tower but don't know how.

LG Andre and happy holidays!!!!

**Comment by QIDITECH** [comment]
We will fix this bug in the next release.
 If you prefer to return material, you can modify the M603 code in print.cfg via fluidd.
About cleaning tower, you can add a column to the print platform, or set up multi-color printing, and start the wipe tower.
![image](https://github.com/QIDITECH/QIDI_MAX3/assets/37525539/8ce9bf6a-04e1-4bf3-bcda-061cd9e1eb46)
![image](https://github.com/QIDITECH/QIDI_MAX3/assets/37525539/705cc61c-cbc1-44a5-8866-04bf1ac23cec)
