### ISSUE TITLE
Please provide an .stl of the printbed

### ISSUE THREAD

**Issue by Phil1988** [QIDITECH/QIDI_MAX3#19]
It would be nice if you could share the .stl file of the print bed, so we can import that to our favorite slicer.

on QidiSlicer it looks like this:
![image](https://github.com/QIDITECH/QIDI_MAX3/assets/6054234/4115caeb-5cb4-4f8d-94cc-039257ac74d4)

while on PrusaSlicer the printbed looks like this:
![image](https://github.com/QIDITECH/QIDI_MAX3/assets/6054234/1c94459a-5e01-41e6-8555-21da8b2cd32d)

if you could share the .stl file we will all have the nice looking printbed on our slicers.

Thanks in advance :)

**Comment by andy775** [comment]
Phil,
[QIDISlicer_bed_stls.zip](https://github.com/QIDITECH/QIDI_MAX3/files/13802090/QIDISlicer_bed_stls.zip)

STL of bed images can be found in the installation directory of qidi slicer. I've attached the stls found in the path. 

Check the following path:

\\Program Files\QIDISlicer\resources\profiles\QIDITechnology

Happy New Year :)

**Comment by Phil1988** [comment]
Thanks @andy775 that helped a lot ^^
