### ISSUE TITLE
Kann nicht Updaten

### ISSUE THREAD

**Issue by Anelke** [QIDITECH/QIDI_MAX3#24]
wollte von 4.3.12 auf 4.3.13 updaten und es geht nicht? Drucker zeigt mir keine update möglichkeit

**Comment by pmbroth** [comment]
did you copy the update files to the usb in the update foldeer, along with choosing the ciorrect printewr cfg file

**Comment by Anelke** [comment]
Was ist denn die Aktualisierung mapp  Gesendet von Mail für Windows Von: pmbrothGesendet: Mittwoch, 17. Januar 2024 02:20An: QIDITECH/QIDI_MAX3Cc: Anelke; AuthorBetreff: Re: [QIDITECH/QIDI_MAX3] Kann nicht Updaten (Issue #24) did you copy the update files to the usb in the update foldeer, along with choosing the ciorrect printewr cfg file—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Anelke** [comment]
Dankeschön 
Hat sich alles Erledigt, mein Fehler

Weiter so Lieben Gruß Andre
