### ISSUE TITLE
Wrong code in events.cpp

### ISSUE THREAD

**Issue by fran6p** [QIDITECH/QIDI_MAX3#25]
Hi,
Version 4.3.13
Even if it won't block the command, it would be good to correct the feed in this line of code ([line 2827](https://github.com/QIDITECH/QIDI_MAX3/blob/320abec5583dd24dd03b3771e45900601f2c8506/src/event.cpp#L2827))

ep->Send(json_run_a_gcode("G0 Z50 F600\nG1 X0 Y0 G9000\nSAVE_CONFIG"));

should be 

ep->Send(json_run_a_gcode("G0 Z50 F600\nG1 X0 Y0 **F**9000\nSAVE_CONFIG"));

**Comment by QIDITECH** [comment]
Thanks for your reminding, we will change it immediately.
