### ISSUE TITLE
IP address for remote access

### ISSUE THREAD

**Issue by mirspan** [QIDITECH/QIDI_MAX3#26]
Add option to manually enter ip address for remote access to 3D printer. It would be permanently saved and used indefinitely.

**Comment by QIDITECH** [comment]
The IP address is determined and assigned by the router.
There is no static IP solution that can be adapted to all routers.

**Comment by trancified** [comment]
Note, it doesn't need to be implemented to interface with a router. It can advertise its own hotspot, with a name.local address.

Sent via the Samsung Galaxy S20+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
