### ISSUE TITLE
Software shutdown of the 3D printer

### ISSUE THREAD

**Issue by mirspan** [QIDITECH/QIDI_MAX3#31]
Add 3D printer software shutdown function.  
 
1. In the menu, the user would select the shutdown item.
2. And only when prompted would the user physically turn off the button on the 3D printer.

The current state of affairs is not conducive to the Linux platform on which Klipper runs.

**Comment by QIDITECH** [comment]
Unfortunately, x-max3 hardware does not support this feature.
