### ISSUE TITLE
Klipper crash after update firmware  4.3.13

### ISSUE THREAD

**Issue by mirspan** [QIDITECH/QIDI_MAX3#32]
Klipper randomly started crashing after updating firmware to version 4.3.13.

I print the first copy without a problem and on the second one it crashes at different times.

**Comment by Anelke** [comment]
Habe ich auch mehrmals so erlebt, soll wohl nur der Tausch des Boards am Kopf helfen.
I've experienced this several times, and the only thing that should help is replacing the board on the head.

**Comment by mirspan** [comment]
Because it terminates spontaneously Klipper. At least that's how it's defined in the web interface. This looks more like a software bug. I reinstalled the firmware yesterday and will see if that helps. 

Before that it started to get angry after 20 days after the update.

**Comment by QIDITECH** [comment]
Sorry, I can't understand what you mean. Could you please provide pictures to tell me the error report on the printer and what happened?

**Comment by CChen616** [comment]
If klipper crashes again, please copy the error message showed in fluidd page here, and append the klipper.log for troubleshooting.
