### ISSUE TITLE
Max Volumetric Speed calibration size too big

### ISSUE THREAD

**Issue by Mike3987** [QIDITECH/QIDI_MAX3#36]
In the Qidi Slicer, I click calibration under the menu. There is a new option called Max Volumetric Speed. The object does not fit in the x-smart 3 print bed. I cannot do the calibration.

**Comment by QIDITECH** [comment]
Yes, this is the standard test model, so we need to test if scaling down the model will affect the test.
We will fix this issue in the next release. Disable or reduce.

**Comment by Mike3987** [comment]
Thanks, Can you also add a max volumetric speed calibration tutorial guide. In the Qidi slicer, there is a section for tutorials. Currently there are tutorials only for pressure advance and flow rate. There isn't one for volumetric speed calibration.

**Comment by Fisheye3D** [comment]
> Yes, this is the standard test model, so we need to test if scaling down the model will affect the test. We will fix this issue in the next release. Disable or reduce.

Scaling down doesn't effect the test as its a based on layer height not time per layer.

**Comment by QIDITECH** [comment]
We have added this feature and will be releasing a new version next week.
