### ISSUE TITLE
Bed scratched when no PEI plate present

### ISSUE THREAD

**Issue by ffries** [QIDITECH/QIDI_MAX3#37]
Hello,

I am a user of the QIDI MAX 3 and I posted the issue on a user forum:
https://www.lesimprimantes3d.fr/forum/topic/57691-lit-qidi-x-max-3-endommag%C3%A9-solutions

This is what happens if a print is launched without PEI plate : 
* Print head goes down. Bed is in aluminium, so it is not detected. 
* Print head scratchs and destroys the bed.

Is there a software way to avoid this situation?

Kind regards,
![IMG_2641](https://github.com/QIDITECH/QIDI_MAX3/assets/25719361/f48f384f-ade4-472d-9826-aedf33122cfc)

**Comment by Fisheye3D** [comment]
No, This is something that should be taken into account when using any type of inductive sensor. Reading your forum post you give the following reasons why it happened.

1: poor factory settings: How is it poor factory settings because you left the pei plate off, this would happen with any printer that uses inductive probes

2: absence of a endstop in Z: Im not sure if you are new to 3d printing but your z endstop is your probe if you're using one.

3: replacement of the BL-touch with an inductive sensor not working without a PEI plate: this is how it works and always has, maybe you would be better with the bl touch.  

In your post even though you say why it happened and know why it happened you still are trying to blame Qidi for it. I'm confused how it would be their fault.

**Comment by CChen616** [comment]
As @Fisheye3D  mentioned, this happens to most printers on the market. We will supplement our Wiki with additional explanations regarding this issue.

**Comment by drewp29** [comment]
Fisheye3D

While I agree mostly with your comments, #2 is absolutely valid. There is an open input on the MKS board specifically for a Z endstop sensor, and IMHO it should have been used. The induction sensor and virtual endstop are okay, but there are situations in which having an actual endstop sensor would be very beneficial. For instance, I did not realize that if you run a bed mesh calibration and accept the mesh in Fluidd, then press the confirm button on the touchscreen, the printer forgets where the bed is and proceeds to ram the nozzle into the bed. This was with the PEI plate fully present, so the induction sensor did absolutely nothing to stop it from happening. Luckily, the nozzle was parked slightly off the edge of the PEI plate and only put a divot in the corner of the magnetic sheet. Had the PEI plate been slightly off the edge of the magnetic sheet it would have impacted the spring steel and probably fractured my ruby-tipped nozzle. A mechanical endstop would have prevented this.

Now, whether or not this is the way most other printers do it as well, doesn't make it the right way to do it.

**Comment by Fisheye3D** [comment]
> Fisheye3D
> 
> While I agree mostly with your comments, #2 is absolutely valid. There is an open input on the MKS board specifically for a Z endstop sensor, and IMHO it should have been used. The induction sensor and virtual endstop are okay, but there are situations in which having an actual endstop sensor would be very beneficial. For instance, I did not realize that if you run a bed mesh calibration and accept the mesh in Fluidd, then press the confirm button on the touchscreen, the printer forgets where the bed is and proceeds to ram the nozzle into the bed. This was with the PEI plate fully present, so the induction sensor did absolutely nothing to stop it from happening. Luckily, the nozzle was parked slightly off the edge of the PEI plate and only put a divot in the corner of the magnetic sheet. Had the PEI plate been slightly off the edge of the magnetic sheet it would have impacted the spring steel and probably fractured my ruby-tipped nozzle. A mechanical endstop would have prevented this.
> 
> Now, whether or not this is the way most other printers do it as well, doesn't make it the right way to do it.

I understand its a valid concern but this is how Klipper works, It uses your probe as a Zendstop, Every printer that uses a probe and Klipper this is how it is done, not saying its correct or safe always and ill admit the way Qidi implemented the screen firmware causes a lot of the issues and non of those would prob happen if they used reg Klipper save options and klipperscreen instead from the beginning as it would then alleviated a lot of these issues.
