### ISSUE TITLE
Implement G28+SCREWS_TILT_CALCULATE

### ISSUE THREAD

**Issue by ffries** [QIDITECH/QIDI_MAX3#40]
Hello,

Could you implement G28+SCREWS_TILT_CALCULATE
which is standard on Klipper and would help users fine-tune the bed level.

Kind regards,

**Comment by Fisheye3D** [comment]
You already can, Just add this to your config

[screws_tilt_adjust]
horizontal_move_z: 4
screw_thread: CCW-M4
speed: 300

screw1: 7,37
screw1_name: front left
screw2: 262,37
screw2_name: front right
screw3: 262,297
screw3_name: rear right
screw4: 7,297
screw4_name: rear left

Then in your console use the command SCREWS_TILT_CALCULATE it will probe all 4 corners and give you a readout to tell you how much to turn the screws.

> Hello,
> 
> Could you implement G28+SCREWS_TILT_CALCULATE which is standard on Klipper and would help users fine-tune the bed level.
> 
> Kind regards,
