### ISSUE TITLE
More information needed on Z geometry

### ISSUE THREAD

**Issue by ffries** [QIDITECH/QIDI_MAX3#41]
Hello,

I was able to fine tune Z-level using bed screws, but after several Z collisions, the Z geometry is not fine. There is possibly a difference between Z left main screw and Z right main screw. 

Is there a standard documentation explaining how to set Z screws BEFORE leveling with bed screws.

Kind regards,

**Comment by CChen616** [comment]
For this issue, you can contact our customer service. They will provide you with a detailed video on how to set  Z screws.
