### ISSUE TITLE
Printer CFG still shows older version 4.3.11

### ISSUE THREAD

**Issue by Waynedejager1** [QIDITECH/QIDI_MAX3#42]
I see the printer.cfg version still shows 4.3.11 in the new 4.3.13 firmware but i do see a few line changes at 875 - 877 ( filament unload ). 

Im not sure what other differences there are between this 4.3.11 ( firmware 4.3.13) and the original 4.3.11 ( firmware 4.3.12 ) and wonder if the Z height issue is not impacted hereby.....

either way the latest firmware printer.cfg contains a version line error.....

**Comment by CChen616** [comment]
Yes, there is indeed an issue with the version number at present. As for saving the z-offset to `config.mksini`, this has been implemented many versions ago, and reverting it might cause numerous problems.
