### ISSUE TITLE
Control board Fan constantly on. Can you disable it when not in use?

### ISSUE THREAD

**Issue by 4eyez19** [QIDITECH/QIDI_MAX3#45]
There is a fan, i think its for the control board that constantly runs, even when the printer is in sleep/standby mode.

The bambu x1c had the same issue when it first released but they updated it to be silent when not in use.

is there a way to disable this as its very annoying and waste of power.

Thanks

**Comment by Fisheye3D** [comment]
> There is a fan, i think its for the control board that constantly runs, even when the printer is in sleep/standby mode.
> 
> The bambu x1c had the same issue when it first released but they updated it to be silent when not in use.
> 
> is there a way to disable this as its very annoying and waste of power.
> 
> Thanks

Its connected to an always-on non-pwm fan port so no way to disable it.

**Comment by 4eyez19** [comment]
> > There is a fan, i think its for the control board that constantly runs, even when the printer is in sleep/standby mode.
> > The bambu x1c had the same issue when it first released but they updated it to be silent when not in use.
> > is there a way to disable this as its very annoying and waste of power.
> > Thanks
> 
> Its connected to an always-on non-pwm fan port so no way to disable it.

thats unfortunate :(

I guess there is no other solution?

**Comment by CChen616** [comment]
I'm sorry, but yes, currently, the mainboard on the Max model does not have spare pins for fan control, and it uses a direct power connection instead. However, you can contact after-sales service to replace the fan in order to minimize noise caused by dust accumulation or other reasons.

**Comment by 4eyez19** [comment]
> I'm sorry, but yes, currently, the mainboard on the Max model does not have spare pins for fan control, and it uses a direct power connection instead. However, you can contact after-sales service to replace the fan in order to minimize noise caused by dust accumulation or other reasons.

is the led light powered by the same voltage as the fan? if so, could i join them together somehow so when the light is on when waking the machine, the power will go to the fan also?

**Comment by CChen616** [comment]
Yes, they are the same.

**Comment by leadustin** [comment]
> Yes, they are the same.

Can you provide a diagram of the X-Max/Plus-3? In the official wiki there is a picture of the mainboard with numbered pins. But there are a few plug contacts that are not described. 2 pieces to the left of connector 16, 1x to the right of connector 16. Then there are 2 USB connectors next to pin 4. I would like to know what the technical specs are.

**Comment by Fisheye3D** [comment]
> > Yes, they are the same.
> 
> Can you provide a diagram of the X-Max/Plus-3? In the official wiki there is a picture of the mainboard with numbered pins. But there are a few plug contacts that are not described. 2 pieces to the left of connector 16, 1x to the right of connector 16. Then there are 2 USB connectors next to pin 4. I would like to know what the technical specs are.

Are you talking about this? 
![image](https://github.com/QIDITECH/QIDI_MAX3/assets/78997080/f95745d9-1ad5-44e9-af12-f05d1c52a56c)

**Comment by leadustin** [comment]
> > > Yes, they are the same.
> > 
> > 
> > Can you provide a diagram of the X-Max/Plus-3? In the official wiki there is a picture of the mainboard with numbered pins. But there are a few plug contacts that are not described. 2 pieces to the left of connector 16, 1x to the right of connector 16. Then there are 2 USB connectors next to pin 4. I would like to know what the technical specs are.
> 
> Are you talking about this? ![image](https://private-user-images.githubusercontent.com/78997080/324527421-f95745d9-1ad5-44e9-af12-f05d1c52a56c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDE0OTEsIm5iZiI6MTcxMzgwMTE5MSwicGF0aCI6Ii83ODk5NzA4MC8zMjQ1Mjc0MjEtZjk1NzQ1ZDktMWFkNS00NGU5LWFmMTItZjA1ZDFjNTJhNTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE1NTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NzY5ZmEwMTNjMTdhMGMzOTU3YTZkMDI1MjM0ZTQ4OTM2MzRhZGZkOWI5N2Y4YjYzZTZjM2RjNDliN2MyMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tepY7L5v9hCHTpg3Hxm0q48zp1LgaIfr_380ZUgKJXg)

That's exactly what I meant. Any idea what the H-USB and M-USB ports are for?

**Comment by Fisheye3D** [comment]
> > > > Yes, they are the same.
> > > 
> > > 
> > > Can you provide a diagram of the X-Max/Plus-3? In the official wiki there is a picture of the mainboard with numbered pins. But there are a few plug contacts that are not described. 2 pieces to the left of connector 16, 1x to the right of connector 16. Then there are 2 USB connectors next to pin 4. I would like to know what the technical specs are.
> > 
> > 
> > Are you talking about this? ![image](https://private-user-images.githubusercontent.com/78997080/324527421-f95745d9-1ad5-44e9-af12-f05d1c52a56c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDE0OTEsIm5iZiI6MTcxMzgwMTE5MSwicGF0aCI6Ii83ODk5NzA4MC8zMjQ1Mjc0MjEtZjk1NzQ1ZDktMWFkNS00NGU5LWFmMTItZjA1ZDFjNTJhNTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE1NTMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NzY5ZmEwMTNjMTdhMGMzOTU3YTZkMDI1MjM0ZTQ4OTM2MzRhZGZkOWI5N2Y4YjYzZTZjM2RjNDliN2MyMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tepY7L5v9hCHTpg3Hxm0q48zp1LgaIfr_380ZUgKJXg)
> 
> That's exactly what I meant. Any idea what the H-USB and M-USB ports are for?

That has been a mystery ive been trying to figure out myself, Nothing on the skpr board these are cloned from gives any clues either.

**Comment by CChen616** [comment]
They are used for debugging different chips.
![image](https://github.com/QIDITECH/QIDI_MAX3/assets/88018764/76e5524b-706c-449c-aa92-9e0bdaf56d38)

**Comment by leadustin** [comment]
> They are used for debugging different chips. ![image](https://private-user-images.githubusercontent.com/88018764/324651295-76e5524b-706c-449c-aa92-9e0bdaf56d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTQ5MjIsIm5iZiI6MTcxMzg1NDYyMiwicGF0aCI6Ii84ODAxODc2NC8zMjQ2NTEyOTUtNzZlNTUyNGItNzA2Yy00NDljLWFhOTItOWUwYmRhZjU2ZDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA2NDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNmUzZjVlM2E3MjZmZDVjYzMxYTZhNTU2MGI3ZDQ1ODIzZTE4ODZiM2I4YzJkMWY3NzMwYjgyN2FkZDcyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZPdgFswcMI7xhIuBQ1Fv9lpIiezLVZbwBychsVAyZ_Y)

Is there a way to use PA 11 and PA12 to control a fan/sensor etc.? Is the port voltage 5 volts as standard?

**Comment by CChen616** [comment]
As a debugging port, it does not provide sufficient voltage output. You might consider paralleling it with an existing LED light or fan. If you want to install additional sensors, you could consider paralleling several fans together to free up pins for the sensors.
