### ISSUE TITLE
Security Issue / Question - Why is my Max3 sending outbound traffic to arksine.github.io?

### ISSUE THREAD

**Issue by leckert123** [QIDITECH/QIDI_MAX3#54]
Just got my X-Max3 2 days ago, and have been printing up a storm. The machine is awesome. It is connected by Ethernet to my network.  As a routine security check, whenever new devices are added to my network, the hardware firewall traffic logs were reviewed. I like to see if anything "interesting" is going on.  Good gosh, yes.

Tons and tons of outbound traffic is being sent to **arksine.github.io**

1. Why? 
2. What is being sent?
3. Is that data then being routed forward to someplace else that we should know about?
4. Is it merely Klipper or Moonraker checking ever few minutes to see if they are up to date? Seems a bit excessive, eh?
5. I can block that traffic...but what would happen?

I bought a Qidi, in part, to avoid the BBL backdoor data issues. Is my lovely X-Max3 doing anything nefarious? 

![20240609_Firewall](https://github.com/QIDITECH/QIDI_MAX3/assets/41870928/63a92d52-d8c5-4b2e-9cf3-91a45f27abfd)

**Comment by Fisheye3D** [comment]
Its moonraker and klipper https://github.com/Arksine web api service and cam service

**Comment by leckert123** [comment]
Thank you. I think.  No data is coming back. It's all one way. My machine is sending data to arksine, but none coming back. I'm dumb.

**Comment by Fisheye3D** [comment]
> Thank you. I think. No data is coming back. It's all one way. My machine is sending data to arksine, but none coming back. I'm dumb.

The reason you see it over and over is because its moonrakers update API that qidi has blocked

**Comment by leckert123** [comment]
Ah, then that's a good thing.  Because otherwise a Moonraker update would brick my machine!

**Comment by leckert123** [comment]
Thank you, Fisheye3D.
