### ISSUE TITLE
Gcode Preview , can not use!!!  I can't see the current level and progress.

### ISSUE THREAD

**Issue by Lovelace3314** [QIDITECH/QIDI_MAX3#60]
<img width="577" alt="E`V5AS$0)9HXYRYPZZK$DDA" src="https://github.com/user-attachments/assets/9b5edaaa-f220-4916-aaf0-658e33736ea0">

**Comment by QIDITECH** [comment]
Try clicking to load the current file.
If it doesn't work, please share your gcode with us.

**Comment by Lovelace3314** [comment]
tks,Problem solved.
