### ISSUE TITLE
Sound button

### ISSUE THREAD

**Issue by KazakovAndrey** [QIDITECH/QIDI_MAX3#71]
Hi!
The sound button always reverts to "off" after you power down. Is there a way to save it on?

**Comment by QIDITECH** [comment]
You can do this by modifying the value in print.cfg in fluidd.
![image](https://github.com/user-attachments/assets/146e0b63-2389-4bb3-b2f3-5720b72cab5e)

**Comment by KazakovAndrey** [comment]
This doesn't solve the problem. 
This section exist in print.cfg by default from firmware.

**Comment by QIDITECH** [comment]
After changing the value from 0 to 1, save and restart the printer.

**Comment by KazakovAndrey** [comment]
I try, but nothing has changed.

look cosole after start and see beep_off
![изображение](https://github.com/user-attachments/assets/7d2735dd-903c-4628-928c-3f8cc1f7f11c)

**Comment by QIDITECH** [comment]
You need to change the value of output_pin sound, not beeper.
Or you can send your print.cfg file to me, and I will modify it and send it to you.
