### ISSUE TITLE
When loading the printer with filament, input the weight\length of filament

### ISSUE THREAD

**Issue by trancified** [QIDITECH/QIDI_MAX3#8]
When loading the printer with filament, input the weight\length of filament so that *before* a print is sent to the printer (the slicer queries the printer of the jobs since the last filament change) can determine if there is enough filament to complete the job.

tl;dr, have better indicators as to whether or not there is enough filament to complete the job.

**Comment by Rainboooom** [comment]
What do you mean is that the printer displays the weight and length information of the currently loaded consumables, so that it can determine whether printing can be completed before sending the print file?

**Comment by trancified** [comment]
Lemme see if I can explain. A standard roll of filament is 1KG. If you told the machine that you were loading 1KG then it would know based on the jobs being sent to it, how much of the roll would be left before needing a roll change. If a user could query this info before a job was sent, they could optimize their jobs so they could minimize the chances of running out of filament in the middle of a job.

Does that make sense?
________________________________

**Comment by Rainboooom** [comment]
Regarding the issue of weight detection, my colleagues and I have discussed it. If we simply make a version that can provide feedback on the weight of consumables and automatically subtract the printing weight by obtaining printing information, and simply provide feedback on the printing situation, the machine cannot effectively meet various usage conditions. What if we cancel printing midway and replace it with another printed file? If there is an unexpected interruption in the printing process, then the record of this weight is meaningless. It is best to directly install an additional weight sensor to directly detect the weight of consumables. However, this involves a new product. What do you think of this product if it is a simple weight display box?

**Comment by Rainboooom** [comment]
Thank you very much for your feedback. We will try to come up with a reliable solution.

**Comment by trancified** [comment]
I'd be more than happy to help in any way I can. I can do code reviews at a minimum.

Sent via the Samsung Galaxy S20+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by QIDITECH** [comment]
The above solutions are not complete, different users will have different problems, we will design a complete solution before use.
