### ISSUE TITLE
Manual IP address information

### ISSUE THREAD

**Issue by MarkusKgit** [QIDITECH/QIDI_MAX3#9]
Good day,

could you make it possible to enter IP address and DNS information manually for LAN connections in an upcoming version? Our network does not run a DHCP server, instead IP addresses are manually allocated. I'd love to control the printer with the Klipper UI remotely in our network.

Thank you,
Markus

**Comment by QIDITECH** [comment]
I'm sorry, it's not available yet, but we're actively working on it, but it's going to take a while.
